package com.shanbay.reader.dao;

import com.shanbay.reader.model.bean.Lesson;
import com.shanbay.reader.model.bean.Word;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

	private final DaoConfig lessonDaoConfig;
	private final DaoConfig wordDaoConfig;

	private final LessonDao lessonDao;
	private final WordDao wordDao;

	public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
			daoConfigMap) {
		super(db);

		lessonDaoConfig = daoConfigMap.get(LessonDao.class).clone();
		lessonDaoConfig.initIdentityScope(type);

		wordDaoConfig = daoConfigMap.get(WordDao.class).clone();
		wordDaoConfig.initIdentityScope(type);

		lessonDao = new LessonDao(lessonDaoConfig, this);
		wordDao = new WordDao(wordDaoConfig, this);

		registerDao(Lesson.class, lessonDao);
		registerDao(Word.class, wordDao);
	}

	public void clear() {
		lessonDaoConfig.clearIdentityScope();
		wordDaoConfig.clearIdentityScope();
	}

	public LessonDao getLessonDao() {
		return lessonDao;
	}

	public WordDao getWordDao() {
		return wordDao;
	}

}
